services:
  postgres:
    image: postgres:16.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    ghy1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=dev
      - SECRET_KEY_BASE=some_dev_secret_key
    # ports:
    #   - "4000:4000"
    networks:
      - ghy_network
    restart: unless-stopped
    volumes:
      - ghy1_data:/app/data

  ghy2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=dev
      - SECRET_KEY_BASE=some_dev_secret_key
    # ports:
    #   - "4001:4001"
    networks:
      - ghy_network
    restart: unless-stopped
    volumes:
      - ghy2_data:/app/data

volumes:
  db_data: