services:
  postgres:
    image: postgres:16.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  luia1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=dev
      - SECRET_KEY_BASE=some_dev_secret_key
      - ENV=container
    ports:
       - "4000:4000"
    restart: unless-stopped
    networks:
      - default

  luia2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=dev
      - SECRET_KEY_BASE=some_dev_secret_key
      - ENV=container
    ports:
       - "4001:4000"
    restart: unless-stopped
    networks:
      - default

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - luia1
      - luia2
    restart: unless-stopped
    networks:
      - default

volumes:
  db_data:

networks:
  default: